/*
*BANCO CRIADO COM CARINHO POR IGHOR DRUMMOND.
*DATA: 23/05/2024
*OBJETIVO: INSERIR PRODUTOS E SUAS RESPECTIVAS IMAGENS AO BANCO DE DADOS
*/	
/*
1 tamanho 34
2 tamanho 35
3 tamanho 36
4 tamanho 37
5 tamanho 38
6 tamanho 39
7 tamanho 40
8 tamanho 41
9 tamanho 42
10 tamanho 43
11 tamanho 44
# TAMANHO PARA HOMENS: '6;7;8;9;10;11'
# TAMANHO PARA JOVEM: '1'
# TAMANHO PARA FEMININAS: '3;4;5;6'
*/
USE db_aerofusion;

#INSIRINDO PRODUTOS
INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('PARIS SAINT-GERMAIN X AIR JORDAN 1 HIGH ZOOM COMFORT', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 1310.09, 50, FALSE, '6;7;8;9;10;11', 2 );

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 MID CHICAGO BLACK TOE', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 1099.99, 50, FALSE, '6;7;8;9;10;11', 2 );

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 RETRO HIGH OG HYPER ROYAL', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 1319.97, 35, FALSE, '6;7;8;9;10;11', 2 );

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 MID SE ALL-STAR WEEKEND CARBON', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 1099.97, 45, FALSE, '3;4;5;6', 3 );

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, promocao ,tamanho, id_cat, vizu_3d, obj_3d) 
VALUES('TÊNIS AIR JORDAN 1 RETRO HIGH OG "PANDA" TWIST', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 1207.77, 50, TRUE, 1099.99 ,'6;7;8;9;10;11', 2, TRUE, 'air_jordan_1.glb' );

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS WMNS AIR JORDAN 1 MID CACTUS FLOWER', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 897.97, 50, FALSE, '3;4;5;6', 3 );

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 HIGH RETRO OG POLLEN', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 1209.99, 65, FALSE, '6;7;8;9;10;11', 2 );

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 MID PINE GREEN', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 769.99, 35, FALSE, '6;7;8;9;10;11', 2 );

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 RETRO HIGH OG UNIVERSITY BLUE', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 1099.99, 50, FALSE, '6;7;8;9;10;11', 2 );

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 RETRO HIGH OG WMNS TIE-DYE', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 989.99, 70, FALSE, '6;7;8;9;10;11', 2 );

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 HIGH ZOOM RACER BLUE', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 1097.77, 0, FALSE, '6;7;8;9;10;11', 2 );

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 MID SE PS ICE CREAM', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 879.99, 20, FALSE, '6;7;8;9;10;11', 3 );

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 MID SE ELECTRO ORANGE', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 769.99, 35, FALSE, '6;7;8;9;10;11', 2);

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 RETRO MID SE "CRIMSON TINT/HYPER PINK"', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 877.77, 45, FALSE, '3;4;5;6', 3);

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 RETRO HIGH TOKYO BIO HACK', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 1317.77, 25, FALSE, '6;7;8;9;10;11', 2);

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 HIGH OG WMNS "UNC TO CHICAGO"', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 1097.78, 45, FALSE, '6;7;8;9;10;11', 2);

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('J. BALVIN X AIR JORDAN 1 RETRO OG HIGH COLORES Y VIBRAS', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 1429.99, 78, FALSE, '6;7;8;9;10;11', 2);

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 MID SE TURF ORANGE', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 824.99, 25, FALSE, '6;7;8;9;10;11', 2);

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 MID SE TURF ORANGE', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 824.99, 25, FALSE, '6;7;8;9;10;11', 2);

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS AIR JORDAN 1 HIGH SWITCH LIGHT SMOKE GRAY', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 1429.99, 25, FALSE, '6;7;8;9;10;11', 2);

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS WMNS AIR JORDAN 1 RETRO HIGH OG SATIN RED', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 799.99, 25, FALSE, '6;7;8;9;10;11', 2);

INSERT INTO produtos(nome, descricao, preco, estoque, promocao_ativo, tamanho, id_cat) 
VALUES('TÊNIS WMNS AIR JORDAN 1 MID DIGITAL PINK', 'DESDE SEU LANCE VENCEDOR EM 1985, MICHAEL JORDAN TEM SIDO UMA LENDA NO BASQUETE. COM O AIR JORDAN I, ELE MUDOU O JOGO, ESTABELECENDO NOVOS PADRÕES E DESAFIANDO AS REGRAS DA LIGA. A LINHA AIR JORDAN CONTINUA A LIDERAR O MUNDO DOS CALÇADOS DE BASQUETE.', 1299.99, 25, FALSE, '6;7;8;9;10;11', 3);

#INSIRINDO IMAGENS DOS PRODUTOS
INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 1/Air Jordan 1.webp', 'PRODUTO 1/Air Jordan 1.2.webp', 'PRODUTO 1/Air Jordan 1.3.webp', 'PRODUTO 1/Air Jordan 1.4.webp', 'PRODUTO 1/Air Jordan 1.5.webp', 1);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 2/Air Jordan 1.webp', 'PRODUTO 2/Air Jordan 1.2.webp', 'PRODUTO 2/Air Jordan 1.3.webp', 'PRODUTO 2/Air Jordan 1.4.webp', 'PRODUTO 2/Air Jordan 1.5.webp', 2);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 3/Air Jordan 1.webp', 'PRODUTO 3/Air Jordan 1.2.webp', 'PRODUTO 3/Air Jordan 1.3.webp', 'PRODUTO 3/Air Jordan 1.4.webp', 'PRODUTO 3/Air Jordan 1.5.webp', 3);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 4/Air Jordan 1.webp', 'PRODUTO 4/Air Jordan 1.2.webp', 'PRODUTO 4/Air Jordan 1.3.webp', 'PRODUTO 4/Air Jordan 1.4.webp', 'PRODUTO 4/Air Jordan 1.5.webp', 4);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 5/Air Jordan 1.webp', 'PRODUTO 5/Air Jordan 1.2.webp', 'PRODUTO 5/Air Jordan 1.3.webp', 'PRODUTO 5/Air Jordan 1.4.webp', 'PRODUTO 5/Air Jordan 1.5.webp', 5);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 6/Air Jordan 1.webp', 'PRODUTO 6/Air Jordan 1.2.webp', 'PRODUTO 6/Air Jordan 1.3.webp', 'PRODUTO 6/Air Jordan 1.4.webp', 'PRODUTO 6/Air Jordan 1.5.webp', 6);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 7/Air Jordan 1.webp', 'PRODUTO 7/Air Jordan 1.2.webp', 'PRODUTO 7/Air Jordan 1.3.webp', 'PRODUTO 7/Air Jordan 1.4.webp', 'PRODUTO 7/Air Jordan 1.5.webp', 7);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 8/Air Jordan 1.webp', 'PRODUTO 8/Air Jordan 1.2.webp', 'PRODUTO 8/Air Jordan 1.3.webp', 'PRODUTO 8/Air Jordan 1.4.webp', 'PRODUTO 8/Air Jordan 1.5.webp', 8);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 9/Air Jordan 1.webp', 'PRODUTO 9/Air Jordan 1.2.webp', 'PRODUTO 9/Air Jordan 1.3.webp', 'PRODUTO 9/Air Jordan 1.4.webp', 'PRODUTO 9/Air Jordan 1.5.webp', 9);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 10/Air Jordan 1.webp', 'PRODUTO 10/Air Jordan 1.2.webp', 'PRODUTO 10/Air Jordan 1.3.webp', 'PRODUTO 10/Air Jordan 1.4.webp', 'PRODUTO 10/Air Jordan 1.5.webp', 10);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 11/Air Jordan 1.webp', 'PRODUTO 11/Air Jordan 1.2.webp', 'PRODUTO 11/Air Jordan 1.3.webp', 'PRODUTO 11/Air Jordan 1.4.webp', 'PRODUTO 11/Air Jordan 1.5.webp', 11);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 12/Air Jordan 1.webp', 'PRODUTO 12/Air Jordan 1.2.webp', 'PRODUTO 12/Air Jordan 1.3.webp', 'PRODUTO 12/Air Jordan 1.4.webp', '', 12);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 13/Air Jordan 1.webp', 'PRODUTO 13/Air Jordan 1.2.webp', 'PRODUTO 13/Air Jordan 1.3.webp', 'PRODUTO 13/Air Jordan 1.4.webp', 'PRODUTO 13/Air Jordan 1.5.webp', 13);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 14/Air Jordan 1.webp', 'PRODUTO 14/Air Jordan 1.2.webp', 'PRODUTO 14/Air Jordan 1.3.webp', 'PRODUTO 14/Air Jordan 1.4.webp', 'PRODUTO 14/Air Jordan 1.5.webp', 14);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 15/Air Jordan 1.webp', 'PRODUTO 15/Air Jordan 1.2.webp', 'PRODUTO 15/Air Jordan 1.3.webp', 'PRODUTO 15/Air Jordan 1.4.webp', 'PRODUTO 15/Air Jordan 1.5.webp', 15);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 16/Air Jordan 1.webp', 'PRODUTO 16/Air Jordan 1.2.webp', 'PRODUTO 16/Air Jordan 1.3.webp', 'PRODUTO 16/Air Jordan 1.4.webp', 'PRODUTO 16/Air Jordan 1.5.webp', 16);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 17/Air Jordan 1.webp', 'PRODUTO 17/Air Jordan 1.2.webp', 'PRODUTO 17/Air Jordan 1.3.webp', 'PRODUTO 17/Air Jordan 1.4.webp', 'PRODUTO 17/Air Jordan 1.5.webp', 17);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 18/Air Jordan 1.webp', 'PRODUTO 18/Air Jordan 1.2.webp', 'PRODUTO 18/Air Jordan 1.3.webp', 'PRODUTO 18/Air Jordan 1.4.webp', 'PRODUTO 18/Air Jordan 1.5.webp', 18);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 19/Air Jordan 1.webp', 'PRODUTO 19/Air Jordan 1.2.webp', 'PRODUTO 19/Air Jordan 1.3.webp', 'PRODUTO 19/Air Jordan 1.4.webp', 'PRODUTO 19/Air Jordan 1.5.webp', 19);

INSERT INTO imagens_prod(img1, img2, img3, img4, img5, id_prod) 
VALUES('PRODUTO 20/Air Jordan 1.webp', 'PRODUTO 20/Air Jordan 1.2.webp', 'PRODUTO 20/Air Jordan 1.3.webp', 'PRODUTO 20/Air Jordan 1.4.webp', 'PRODUTO 20/Air Jordan 1.5.webp', 20);